DROP TABLE SITEUSERS;
CREATE TABLE SITEUSERS(
USERID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(50),
USERPASSWORD VARCHAR2(50),
FIRSTNAME VARCHAR2(50),
LASTNAME VARCHAR2(50),
STREET VARCHAR2(50),
CITY VARCHAR2(50),
STATE VARCHAR2(50),
COUNTRY VARCHAR2(50),
ZIPCODE NUMBER,
FAVCOLOR VARCHAR2(50),
FAVANIMAL VARCHAR2(50)
);

--INSERT INTO SITEUSERS VALUES(USERSEQ.NEXTVAL, 'skadu', 'baas', 'Julian', 'Welborn', '4940 SW 151st Ave', 'Davie', 'Florida', 'USA', 33331, 'Red', 'Fox');
--SELECT * FROM SITEUSERS;

--used to autoincrement user ids
--DROP SEQUENCE USERSEQ;
CREATE SEQUENCE USERSEQ
MINVALUE 1
MAXVALUE 10000
START WITH 1
INCREMENT BY 1;

--used to insert new user into table
CREATE OR REPLACE PROCEDURE INSERTUSER(
UNAME IN VARCHAR2,
UPASSWORD IN VARCHAR2,
FNAME IN VARCHAR2,
LNAME IN VARCHAR2,
HSTREET IN VARCHAR2,
HCITY IN VARCHAR2,
HSTATE IN VARCHAR2,
HCOUNTRY IN VARCHAR2,
HZIPCODE IN INTEGER,
FAV_COLOR IN VARCHAR2,
FAV_ANIMAL IN VARCHAR2
)
AS
BEGIN
    INSERT INTO SITEUSERS
    VALUES(USERSEQ.NEXTVAL, UNAME, UPASSWORD, FNAME, LNAME, HSTREET, HCITY, HSTATE, HCOUNTRY, HZIPCODE, FAV_COLOR, FAV_ANIMAL);
    COMMIT;
END;
/

--used to update user's favorites
CREATE OR REPLACE PROCEDURE UPDATE_USER_FAVS(
USER_ID IN INTEGER,
FAV_COLOR IN VARCHAR2,
FAV_ANIMAL IN VARCHAR2
)
AS
BEGIN
    UPDATE SITEUSERS SET FAVCOLOR = FAV_COLOR, FAVANIMAL = FAV_ANIMAL
    WHERE USERID = USER_ID;
    COMMIT;
END;
/

--used to update user's address
CREATE OR REPLACE PROCEDURE UPDATE_USER_INFO(
USER_ID IN INTEGER,
FNAME IN VARCHAR2,
LNAME IN VARCHAR2,
HSTREET IN VARCHAR2,
HCITY IN VARCHAR2,
HSTATE IN VARCHAR2,
HCOUNTRY IN VARCHAR2,
HZIPCODE IN INTEGER
)
AS
BEGIN
    UPDATE SITEUSERS
    SET FIRSTNAME = FNAME, LASTNAME = LNAME, STREET = HSTREET, CITY = HCITY, STATE = HSTATE, COUNTRY = HCOUNTRY, ZIPCODE = HZIPCODE
    WHERE USERID = USER_ID;
    COMMIT;
END;
/

--used to update user's login
CREATE OR REPLACE PROCEDURE UPDATE_USER_LOGIN(
USER_ID IN INTEGER,
UNAME IN VARCHAR2,
UPASSWORD IN VARCHAR2
)
AS
BEGIN
    UPDATE SITEUSERS
    SET USERNAME = UNAME, USERPASSWORD = UPASSWORD
    WHERE USERID = USER_ID;
    COMMIT;
END;
/

--used to delete user info from table
CREATE OR REPLACE PROCEDURE DELETEUSER(USER_ID IN INTEGER)
AS
BEGIN
    DELETE FROM SITEUSERS WHERE USERID = USER_ID;
    COMMIT;
END;
/