package com.example.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-07-31T15:50:44.567-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ws.example.com/", name = "MessageGen")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageGen {

    @WebMethod
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://ws.example.com/", className = "com.example.ws.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://ws.example.com/", className = "com.example.ws.GetMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getMessage();
}
