CREATE TABLE ACCOUNTHOLDER(
    acc_uid NUMBER PRIMARY KEY,
    fname VARCHAR2(50),
    lname VARCHAR2(50),
    uname VARCHAR2(50),
    pass VARCHAR2(50));

CREATE TABLE ACCOUNT(
	accid NUMBER PRIMARY KEY,
	userid NUMBER,
	bal DECIMAL(10,2),
    acc_name VARCHAR2(30),
    CONSTRAINT fk_accountuser FOREIGN KEY(userid) 
    REFERENCES ACCOUNTHOLDER(acc_uid));
    
CREATE TABLE ADMINISTRATOR(
    admid NUMBER,
    aduname VARCHAR2(30),
    adpass VARCHAR2(30),
    CONSTRAINT administrator_pk PRIMARY KEY (admid)
);
/
INSERT INTO ADMINISTRATOR VALUES(NULL, 'MetroTopDog', 'luthor1superman0');

--------------------------------------------------------
--  DDL for Trigger ACCOUNT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JMSULLIVAN93"."ACCOUNT_TRG" 
BEFORE INSERT ON ACCOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACCID IS NULL THEN
      SELECT ACCOUNT_SEQ.NEXTVAL INTO :NEW.ACCID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JMSULLIVAN93"."ACCOUNT_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Trigger ACCOUNTHOLDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JMSULLIVAN93"."ACCOUNTHOLDER_TRG" 
BEFORE INSERT ON ACCOUNTHOLDER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACC_UID IS NULL THEN
      SELECT ACCOUNTHOLDER_SEQ.NEXTVAL INTO :NEW.ACC_UID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JMSULLIVAN93"."ACCOUNTHOLDER_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Trigger ADMINISTRATOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JMSULLIVAN93"."ADMINISTRATOR_TRG" 
BEFORE INSERT ON ADMINISTRATOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADMID IS NULL THEN
      SELECT ADMINISTRATOR_SEQ.NEXTVAL INTO :NEW.ADMID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JMSULLIVAN93"."ADMINISTRATOR_TRG" ENABLE;



