SELECT * FROM EMPLOYEE;

/*

Query MAkeupSELECT [COLUMNLIST] <-REQUIRED

FROM [TABLELIST] <-REQUIRED

WHERE [CONDITION1] AND [CONDITION2]..

GROUP BY [COLUMNLIST]<- GROUP THE RESULTSET. WIDE TO NARROW

                    <- AGGREGATE FUNCTIONS

HAVING [CONDITION] <- USED WITH THE GROUP BY CLAUSE IN A QUERY.

                     TELLS THE GROUP BY WHICH GROUPS TO INCLUDE

                     IN THE OUTPUT

                     <- HAVING IS TO GROUP BY AS WHERE IS TO SELECT

                     <AGGREGATE

ORDER BY [COLUMNLIST] < ASC IS DEFAULT, DESC TO REVERSE

*/

SELECT COUNT(EMPLOYEEID), COUNTRY,CITY

FROM EMPLOYEE

GROUP BY COUNTRY, CITY;

--HAVING COUNT(EMPLOYEEID)>1;

