CREATE TABLE BANKUSERS(
USERID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(30),
USERPASSWORD VARCHAR2(30),
ISADMIN CHAR(1) CHECK (ISADMIN IN ('Y', 'N'))
);

CREATE TABLE BANKACCOUNTS(
ACCTID INT PRIMARY KEY,
ACCTNAME VARCHAR2(30),
AMOUNT NUMBER
);

CREATE SEQUENCE USERSEQ
MINVALUE 1
MAXVALUE 10000
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ACCTSEQ;

CREATE OR REPLACE PROCEDURE INSERTUSER(NAME IN VARCHAR2, ISADMIN IN CHAR)
AS
BEGIN
INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, NAME, ISADMIN);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTACCOUNT(NAME IN VARCHAR2, ISADMIN IN CHAR)
AS
BEGIN
INSERT INTO BANKUSERS VALUES(ACCTSEQ.NEXTVAL, NAME, ISADMIN);
COMMIT;
END;
/