CREATE TABLE BANKUSERS(
USERID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(30),
USERPASSWORD VARCHAR2(30),
ISADMIN CHAR(1) CHECK (ISADMIN IN ('Y', 'N'))
);

DROP TABLE BANKACCOUNTS;
DROP TABLE BANKUSERS;

CREATE TABLE BANKACCOUNTS(
ACCTID INTEGER PRIMARY KEY,
ACCTTYPE VARCHAR2(30),
BALANCE NUMBER,
USERID INTEGER,
CONSTRAINT FK_USER_ID FOREIGN KEY (USERID)
REFERENCES BANKUSERS(USERID)
ON DELETE CASCADE
);

DROP SEQUENCE USERSEQ;
CREATE SEQUENCE USERSEQ
MINVALUE 1
MAXVALUE 10000
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE ACCTSEQ;
CREATE SEQUENCE ACCTSEQ;

--INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, 'Julian', 'frogger', 'Y');
--INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, 'Donkey Kong', 'pauline', 'N');
--INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, 'Master Chief', 'cortana', 'N');
--INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, 'Evan', 'normalman', 'Y');
--INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, 'Michael', 'ground', 'N');

--INSERT INTO BANKACCOUNTS VALUES(ACCTSEQ.NEXTVAL, 'Checking', 1200, 2);
--INSERT INTO BANKACCOUNTS VALUES(ACCTSEQ.NEXTVAL, 'Personal', 500, 3);
--INSERT INTO BANKACCOUNTS VALUES(ACCTSEQ.NEXTVAL, 'Savings', 5000, 2);

--UPDATE BANKUSERS SET USERNAME = 'DonkeyKong' WHERE USERNAME = 'Donkey Kong';

CREATE OR REPLACE PROCEDURE INSERTUSER
(NAME IN VARCHAR2, PASSWORD IN VARCHAR2, ISADMIN IN CHAR)
AS
BEGIN
    INSERT INTO BANKUSERS VALUES(USERSEQ.NEXTVAL, NAME, PASSWORD, ISADMIN);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTACCOUNT
(ACCT_TYPE IN VARCHAR2, AMOUNT IN NUMBER, USER_ID IN INTEGER)
AS
BEGIN
    INSERT INTO BANKACCOUNTS VALUES(ACCTSEQ.NEXTVAL, ACCT_TYPE, AMOUNT, USER_ID);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETEUSER(USER_ID IN INTEGER)
AS
BEGIN
    DELETE FROM BANKACCOUNTS WHERE USERID = USER_ID;
    DELETE FROM BANKUSERS WHERE USERID = USER_ID;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETEACCOUNT(ACCT_ID IN INTEGER)
AS
BEGIN
    DELETE FROM BANKACCOUNTS WHERE ACCTID = ACCT_ID;
    COMMIT;
END;
/