CREATE TABLE BANK(
USERID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(30),
PASSWORD VARCHAR2(30),
ADMINID INTEGER,
BALANCE FLOAT(20)
);

CREATE SEQUENCE USER_ID;
CREATE SEQUENCE BANK_ACCOUNT_ID;
CREATE SEQUENCE ADMIN_ID;

CREATE OR REPLACE PROCEDURE INSERTCUSTOMER(NAME IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
INSERT INTO BANK VALUES(USER_ID.NEXTVAL, BANK_ACCOUNT_ID.NEXTVAL, NULL, NAME, PASSWORD);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTADMIN(NAME IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
INSERT INTO BANK VALUES(USER_ID.NEXTVAL, BANK_ACCOUNT_ID.NEXTVAL, ADMIN_ID.NEXTVAL, NAME, PASSWORD);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE CREATEACCOUNTCUSTOMER(USER_ID IN INT, BANK_ACCOUNT_ID IN INT, NAME IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
INSERT INTO BANK VALUES(USER_ID, BANK_ACCOUNT, NULL, NAME, PASSWORD);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE CREATEACCOUNTADMIN(USER_ID IN INT, BANK_ACCOUNT_ID IN INT, ADMIN_ID IN INT, NAME IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
INSERT INTO BANK VALUES(USER_ID, BANK_ACCOUNT, ADMIN_ID, NAME, PASSWORD);
COMMIT;
END;
/