CREATE SEQUENCE SQ_PK_BANK_USERS2;


CREATE SEQUENCE SQ_PK_USER_ACCOUNTS2;

CREATE SEQUENCE SQ_PK_ADMIN2;

CREATE SEQUENCE SQ_PK_TRANSACTION
MINVALUE 0
INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE GET_ALL_ACCOUNTS
(S OUT SYS_REFCURSOR)
IS 
BEGIN
OPEN S FOR 
SELECT * FROM BANK_USERS ;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_USER
(U_ID IN NUMBER)
IS 
BEGIN
DELETE FROM BANK_USERS WHERE USER_ID=U_ID;
END;
/

call DELETE_USER(10);

CREATE OR REPLACE PROCEDURE DELETE_ACCOUNT
(A_ID IN NUMBER)
IS 
BEGIN
DELETE FROM USER_ACCOUNTS WHERE ACT_ID=A_ID;
COMMIT;
END;
/

ALTER TABLE USER_ACCOUNTS
ADD CONSTRAINT FK_BANK_USERS-- NAME OF CONSTRAINT
FOREIGN KEY(USER_ID) REFERENCES BANK_USERS(USER_ID);

ALTER TABLE TRANSACTION_TABLE
ADD CONSTRAINT FK_USER_ACCOUNTS-- NAME OF CONSTRAINT
FOREIGN KEY(ACT_ID) REFERENCES TRANSACTION_TABLE(ACT_ID);

ALTER TABLE TRANSACTION_TABLE
ADD CONSTRAINT FK_ADMIN_USERS-- NAME OF CONSTRAINT
FOREIGN KEY(ADMIN_ID) REFERENCES TRANSACTION_TABLE(ADMIN_ID);

ALTER TABLE TRANSACTION_TABLE
ADD CONSTRAINT FK_BANK_USERS-- NAME OF CONSTRAINT
FOREIGN KEY(USER_ID) REFERENCES TRANSACTION_TABLE(USER_ID);

INSERT INTO BANK_USERS VALUES(SQ_PK_BANK_USERS2.NEXTVAL,'Chelsea','Stevenson','Miss_Puff','creamball34');

INSERT INTO ADMIN_ACCOUNTS VALUES(SQ_PK_ADMIN2.NEXTVAL,'Miguel','Antigua','MEGA_L','BIGBOYBANK');
COMMIT;
DELETE FROM BANK_USERS WHERE user_id=0;