--these drops are for updating the forms, everything needs to be deleted or improperly formatted data would persist.    
DROP TABLE MESSAGES;
DROP TABLE TUITION_REIMBURSEMENT_FORM;
DROP TABLE EVENT_TYPE_LOOKUP;
DROP SEQUENCE trf_seq;
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEE_TYPE_LOOKUP;


CREATE TABLE EMPLOYEE_TYPE_LOOKUP(
    USER_TYPE_ID VARCHAR2(1),
    USER_TYPE VARCHAR2(20),
    CONSTRAINT PK_USER_TYPE_ID PRIMARY KEY(USER_TYPE_ID)
);

INSERT ALL
INTO EMPLOYEE_TYPE_LOOKUP(USER_TYPE_ID, USER_TYPE) VALUES ('E','EMPLOYEE')
INTO EMPLOYEE_TYPE_LOOKUP(USER_TYPE_ID, USER_TYPE) VALUES ('S', 'SUPERVISOR')
INTO EMPLOYEE_TYPE_LOOKUP(USER_TYPE_ID, USER_TYPE) VALUES ('H', 'DEPARTMENT HEAD')
INTO EMPLOYEE_TYPE_LOOKUP(USER_TYPE_ID, USER_TYPE) VALUES ('B', 'BENEFITS COORDINATOR')
INTO EMPLOYEE_TYPE_LOOKUP(USER_TYPE_ID, USER_TYPE) VALUES ('G', 'GENERAL MANAGER')
SELECT * FROM dual;

CREATE TABLE EMPLOYEE(
    USER_ID NUMBER NOT NULL,
    REFERSTO NUMBER,
    USER_TYPE_ID VARCHAR2(1) DEFAULT 'E',
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    BASIC_INFO_PLACEHOLDER VARCHAR2(100),
    USERNAME VARCHAR2(16) NOT NULL,
    PASSWORD_HASH VARCHAR2(100) NOT NULL,
    AVAILABLE_REIMBURSEMENT NUMERIC(7,2) DEFAULT 1000,
    PENDING_REIMBURSEMENT NUMERIC(7,2) DEFAULT 0,
    AWARDED_REIMBURSEMENT NUMERIC(7,2) DEFAULT 0,
    CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UNI_USERNAME UNIQUE (USERNAME),
    CONSTRAINT USER_TYPE_ID FOREIGN KEY (USER_TYPE_ID) REFERENCES EMPLOYEE_TYPE_LOOKUP(USER_TYPE_ID)
);

INSERT ALL
INTO EMPLOYEE VALUES(-1,NULL,'B', 'Benco', 'Holder', 'BencoMessageHolder', 'BencoMessages', F_ENCRYPT('BefjI2!!^/^k4#4zx'), 1000,0,0)
INTO EMPLOYEE VALUES(1,NULL,'H', 'LEONARA', 'MARSLAND', 'I AM A FEMALE', 'LEONARA1', F_ENCRYPT('MARSLAND1'), 1000,0,0)
INTO EMPLOYEE VALUES(2,1,'S', 'RIKKI', 'TRUMBLE', 'I AM A FEMALE', 'RIKKI1', F_ENCRYPT('TRUMBLE1'), 1000,0,0)
INTO EMPLOYEE VALUES(3,1,'S', 'LINCOLN', 'ELSNER', 'I AM A MALE', 'LINCOLN1', F_ENCRYPT('ELSNER1'), 1000,0,0)
INTO EMPLOYEE VALUES(4,2,'E', 'THERESIA', 'FAULCON', 'I AM A FEMALE', 'THERESIA1', F_ENCRYPT('FAULCON1'), 1000,0,0)
INTO EMPLOYEE VALUES(5,2,'E', 'CHANDRA', 'DELMONTE', 'I AM A FEMALE', 'CHANDRA1', F_ENCRYPT('DELMONTE1'), 1000,0,0)
INTO EMPLOYEE VALUES(6,3,'E', 'CRISELDA', 'HAMMER', 'I AM A FEMALE', 'CRISELDA1', F_ENCRYPT('HAMMER1'), 1000,0,0)
INTO EMPLOYEE VALUES(7,NULL,'H', 'JOHNATHAN', 'BURGHER', 'I AM A MALE', 'JOHNATHAN1', F_ENCRYPT('BURGHER1'), 1000,0,0)
INTO EMPLOYEE VALUES(8,7,'S', 'IGNACIO', 'GIGLIO', 'I AM A MALE', 'IGNACIO1', F_ENCRYPT('GIGLIO1'), 1000,0,0)
INTO EMPLOYEE VALUES(10,8,'E', 'VELIA', 'SCHIMKE', 'I AM A FEMALE', 'VELIA1', F_ENCRYPT('SCHIMKE1'), 1000,0,0)
INTO EMPLOYEE VALUES(11,8,'E', 'KAM', 'SAVARESE', 'I AM A FEMALE', 'KAM1', F_ENCRYPT('SAVARESE1'), 1000,0,0)
INTO EMPLOYEE VALUES(12,7,'E', 'SUSIE', 'BRIERLY', 'I AM A FEMALE', 'SUSIE1', F_ENCRYPT('BRIERLY1'), 1000,0,0)
INTO EMPLOYEE VALUES(13,NULL,'B', 'SHANICE', 'BAUMGART', 'I AM A FEMALE', 'SHANICE1', F_ENCRYPT('BAUMGART1'), 1000,0,0)
INTO EMPLOYEE VALUES(14,NULL,'B', 'MARLIN', 'MODICA', 'I AM A MALE', 'MARLIN1', F_ENCRYPT('MODICA1'), 1000,0,0)
INTO EMPLOYEE VALUES(15,NULL,'G', 'ELOISE', 'PROFITT', 'I AM A FEMALE', 'ELOISE1', F_ENCRYPT('PROFITT1'), 1000,0,0)
SELECT * FROM dual;

CREATE TABLE EVENT_TYPE_LOOKUP(
    EVENT_TYPE_ID VARCHAR2(1),
    EVENT_TYPE VARCHAR2(35),
    REIMBURSEMENT_PERCENTAGE NUMBER,
    CONSTRAINT PK_EVENT_ID PRIMARY KEY (EVENT_TYPE_ID)
);

INSERT ALL
INTO EVENT_TYPE_LOOKUP(EVENT_TYPE_ID, EVENT_TYPE, REIMBURSEMENT_PERCENTAGE) VALUES ('1','UNIVERSITY COURSES', 80)
INTO EVENT_TYPE_LOOKUP(EVENT_TYPE_ID, EVENT_TYPE, REIMBURSEMENT_PERCENTAGE) VALUES ('2', 'SEMINARS', 60)
INTO EVENT_TYPE_LOOKUP(EVENT_TYPE_ID, EVENT_TYPE, REIMBURSEMENT_PERCENTAGE) VALUES ('3', 'CERTIFICATION PREPARATION CLASSES', 75)
INTO EVENT_TYPE_LOOKUP(EVENT_TYPE_ID, EVENT_TYPE, REIMBURSEMENT_PERCENTAGE) VALUES ('4', 'CERTIFICATION', 100)
INTO EVENT_TYPE_LOOKUP(EVENT_TYPE_ID, EVENT_TYPE, REIMBURSEMENT_PERCENTAGE) VALUES ('5', 'TECHNICAL TRAINING', 90)
INTO EVENT_TYPE_LOOKUP(EVENT_TYPE_ID, EVENT_TYPE, REIMBURSEMENT_PERCENTAGE) VALUES ('6', 'OTHER', 30)
SELECT * FROM dual;

CREATE TABLE TUITION_REIMBURSEMENT_FORM(
    TRF_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    BASIC_INFO_PLACEHOLDER VARCHAR2(100) NOT NULL,
    EVENT_DATETIME TIMESTAMP NOT NULL,
    EVENT_LOCATION VARCHAR2(25) NOT NULL,
    EVENT_DESCRIPTION VARCHAR2(200) NOT NULL,
    EVENT_COST NUMERIC(7,2) NOT NULL,
    GRADING_FORMAT VARCHAR2(20) NOT NULL, -- MAYBE CHANGE THIS TO A GRADINGFORMAT ID WHICH WOULD REEFERENCE ANOTHER TABLE
    PASSING_GRADE VARCHAR2(3),
    EVENT_TYPE_ID VARCHAR2(1) NOT NULL,
    WORK_RELATED_JUSTIFICATION VARCHAR2(200) NOT NULL,
    OPTIONAL_ATTACHMENTS_EXIST VARCHAR2(1) DEFAULT 'N', 
    SUPERVISOR_APPROVAL_EXIST VARCHAR2(1) DEFAULT 'N',
    HEAD_APPROVAL_EXIST VARCHAR2(1) DEFAULT 'N',
    BC_APPROVAL VARCHAR2(1) DEFAULT 'N',
    DENIED VARCHAR(1) DEFAULT 'N',
    EXCEEDREASON VARCHAR2(200),
    WORK_TIME_MISSED NUMBER DEFAULT 0,
    PROJECTED_REIMBURSEMENT NUMERIC(7,2), --USE A PROCEDURE TO SET THIS.
    USER_ID NUMBER NOT NULL,
    CONSTRAINT PK_TRF PRIMARY KEY (TRF_ID),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_TYPE_ID) REFERENCES EVENT_TYPE_LOOKUP(EVENT_TYPE_ID),
    CONSTRAINT FK_USER_TRF_ID FOREIGN KEY (USER_ID) REFERENCES EMPLOYEE(USER_ID)
);



CREATE TABLE MESSAGES(
    USER_ID NUMBER NOT NULL,
    MESSAGE VARCHAR2(1000),
    TRF_ID NUMBER NOT NULL,
    FLAG VARCHAR2(2),
    MESSAGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USER_MESSAGE_ID FOREIGN KEY (USER_ID) REFERENCES EMPLOYEE(USER_ID),
    CONSTRAINT FK_TRF_MESSAGE_ID FOREIGN KEY (TRF_ID) REFERENCES TUITION_REIMBURSEMENT_FORM(TRF_ID)
);

CREATE SEQUENCE trf_seq START WITH 1;

CREATE OR REPLACE TRIGGER trf_bir 
BEFORE INSERT ON TUITION_REIMBURSEMENT_FORM 
FOR EACH ROW

BEGIN
  SELECT trf_seq.NEXTVAL
  INTO   :new.trf_id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER trf_reimbursement 
AFTER INSERT ON TUITION_REIMBURSEMENT_FORM 
FOR EACH ROW

BEGIN
    UPDATE EMPLOYEE SET AVAILABLE_REIMBURSEMENT=AVAILABLE_REIMBURSEMENT-:new.PROJECTED_REIMBURSEMENT, PENDING_REIMBURSEMENT=PENDING_REIMBURSEMENT+:new.PROJECTED_REIMBURSEMENT
    WHERE USER_ID=:new.USER_ID;
END;
/

CREATE OR REPLACE FUNCTION LOGIN(IUSERNAME VARCHAR2, IPASSWORD VARCHAR2)
RETURN NUMBER AS IUSER_ID NUMBER; 
DECRYPTED VARCHAR2(100);
BEGIN
    DECRYPTED:=F_ENCRYPT(IPASSWORD);
    SELECT USER_ID INTO IUSER_ID FROM EMPLOYEE WHERE USERNAME=IUSERNAME AND PASSWORD_HASH=DECRYPTED;
    RETURN IUSER_ID;
END;
/

CREATE OR REPLACE FUNCTION GET_EMP_LEVEL(IUSER_ID NUMBER)
RETURN VARCHAR2 AS IUSER_LEVEL VARCHAR2(1);
BEGIN
    SELECT USER_TYPE_ID INTO IUSER_LEVEL FROM EMPLOYEE WHERE USER_ID=IUSER_ID;
    RETURN IUSER_LEVEL;
END;
/

--Direct Supervisor Approve
CREATE OR REPLACE PROCEDURE DSAPPROVE(ITRF_ID IN NUMBER)
IS
BEGIN
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET SUPERVISOR_APPROVAL_EXIST = 'Y' WHERE TRF_ID = ITRF_ID;
    COMMIT;
END;
/
--Dept. Head Approve
CREATE OR REPLACE PROCEDURE DHAPPROVE(ITRF_ID IN NUMBER)
IS
BEGIN
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET HEAD_APPROVAL_EXIST = 'Y' WHERE TRF_ID = ITRF_ID;
    COMMIT;
END;
/
--BenCo Approve
CREATE OR REPLACE PROCEDURE BCAPPROVE(ITRF_ID IN NUMBER)
IS
BEGIN
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET BC_APPROVAL = 'Y' WHERE TRF_ID = ITRF_ID;
    COMMIT;
END;
/
--Deny TRF
CREATE OR REPLACE PROCEDURE TRF_DENIED(ITRF_ID IN NUMBER)
as 
    P_REI NUMERIC(7,2);
    TUSER_ID NUMBER; 
BEGIN
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET DENIED = 'Y' WHERE TRF_ID = ITRF_ID;
    SELECT PROJECTED_REIMBURSEMENT INTO P_REI FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
    SELECT USER_ID INTO TUSER_ID FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
    UPDATE EMPLOYEE SET AVAILABLE_REIMBURSEMENT=AVAILABLE_REIMBURSEMENT+P_REI, PENDING_REIMBURSEMENT=PENDING_REIMBURSEMENT-P_REI
    WHERE USER_ID=TUSER_ID;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE TRF_REQUESTINFO(ITRF_ID IN NUMBER)
IS
BEGIN 
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET DENIED='A' WHERE TRF_ID=ITRF_ID;
    COMMIT;
    END;
/

CREATE OR REPLACE PROCEDURE TRF_GIVENINFO(ITRF_ID IN NUMBER)
IS
BEGIN 
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET DENIED='N' WHERE TRF_ID=ITRF_ID;
    UPDATE MESSAGES 
    SET FLAG='RE' WHERE TRF_ID=ITRF_ID AND FLAG='RI';
    COMMIT;
    END;
/

CREATE OR REPLACE PROCEDURE TRF_WITHDRAW(ITRF_ID IN NUMBER)
IS
BEGIN 
    UPDATE MESSAGES 
    SET FLAG='WA' WHERE TRF_ID=ITRF_ID AND FLAG='AA';
    COMMIT;
    END;
/

CREATE OR REPLACE PROCEDURE TRF_ACCEPT(ITRF_ID IN NUMBER)
IS
BEGIN 
    UPDATE TUITION_REIMBURSEMENT_FORM
    SET DENIED='N' WHERE TRF_ID=ITRF_ID;
    UPDATE MESSAGES 
    SET FLAG='AC' WHERE TRF_ID=ITRF_ID AND FLAG='AA';
    COMMIT;
    END;
/

    
CREATE OR REPLACE FUNCTION GET_BOSS(EMP_LEVEL IN NUMBER, ITRF_ID IN NUMBER) 
RETURN NUMBER AS IUSER_ID NUMBER; 
    SUSER_ID NUMBER;
    HUSER_ID NUMBER;
BEGIN
    IF EMP_LEVEL=1 THEN
        SELECT USER_ID INTO IUSER_ID FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
        RETURN IUSER_ID;
    END IF;
    IF EMP_LEVEL=2 THEN
        SELECT USER_ID INTO IUSER_ID FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
        SELECT REFERSTO INTO SUSER_ID FROM EMPLOYEE WHERE USER_ID=IUSER_ID;
        IF SUSER_ID IS NOT NULL THEN RETURN SUSER_ID; END IF;
        RETURN IUSER_ID;
    END IF;
    IF EMP_LEVEL=3 THEN
        SELECT USER_ID INTO IUSER_ID FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
        SELECT REFERSTO INTO SUSER_ID FROM EMPLOYEE WHERE USER_ID=IUSER_ID;
        IF SUSER_ID IS NOT NULL 
        THEN SELECT REFERSTO INTO HUSER_ID FROM EMPLOYEE WHERE USER_ID=SUSER_ID;
        IF HUSER_ID IS NOT NULL
        THEN RETURN HUSER_ID;
        END IF;
        RETURN SUSER_ID;
        END IF;
        RETURN IUSER_ID;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE REIINCREASE(ITRF_ID IN NUMBER, REI_CHANGE IN NUMBER)
IS
BEGIN
    UPDATE (SELECT E.PENDING_REIMBURSEMENT, E.AVAILABLE_REIMBURSEMENT FROM EMPLOYEE E INNER JOIN TUITION_REIMBURSEMENT_FORM T ON T.USER_ID=E.USER_ID WHERE T.TRF_ID=ITRF_ID) SET PENDING_REIMBURSEMENT=PENDING_REIMBURSEMENT+REI_CHANGE, AVAILABLE_REIMBURSEMENT=AVAILABLE_REIMBURSEMENT-REI_CHANGE;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE REIDECREASE(ITRF_ID IN NUMBER, REI_CHANGE IN NUMBER)
IS
BEGIN
    UPDATE (SELECT E.PENDING_REIMBURSEMENT, E.AVAILABLE_REIMBURSEMENT FROM EMPLOYEE E INNER JOIN TUITION_REIMBURSEMENT_FORM T ON T.USER_ID=E.USER_ID WHERE T.TRF_ID=ITRF_ID) SET PENDING_REIMBURSEMENT=PENDING_REIMBURSEMENT-REI_CHANGE, AVAILABLE_REIMBURSEMENT=AVAILABLE_REIMBURSEMENT+REI_CHANGE;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE TRF_AWARD(ITRF_ID IN NUMBER)
as 
    P_REI NUMERIC(7,2);
    TUSER_ID NUMBER; 
BEGIN
    UPDATE TUITION_REIMBURSEMENT_FORM SET SUPERVISOR_APPROVAL_EXIST='A', HEAD_APPROVAL_EXIST='A', BC_APPROVAL='A' WHERE TRF_ID=ITRF_ID;
    SELECT PROJECTED_REIMBURSEMENT INTO P_REI FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
    SELECT USER_ID INTO TUSER_ID FROM TUITION_REIMBURSEMENT_FORM WHERE TRF_ID=ITRF_ID;
    UPDATE EMPLOYEE SET PENDING_REIMBURSEMENT=PENDING_REIMBURSEMENT-P_REI, AWARDED_REIMBURSEMENT=AWARDED_REIMBURSEMENT+P_REI
    WHERE USER_ID=TUSER_ID;
    COMMIT;
END;
/

CREATE OR REPLACE function timestamp_diff(a timestamp, b timestamp) return number is 
begin
  return extract (day from (a-b));
end;
/

CREATE OR REPLACE PROCEDURE UPDATE_TRF_WITH_TIME
IS
CURSOR L_TRF IS SELECT TRF_ID,TIMESTAMP_DIFF(EVENT_DATETIME,CURRENT_TIMESTAMP) AS DAYS, SUPERVISOR_APPROVAL_EXIST,HEAD_APPROVAL_EXIST ,BC_APPROVAL, USER_ID FROM TUITION_REIMBURSEMENT_FORM WHERE DENIED = 'N';
BEGIN
    FOR I IN L_TRF
        LOOP
        IF (I.SUPERVISOR_APPROVAL_EXIST='N' AND I.DAYS BETWEEN 3 AND 4)THEN
             UPDATE TUITION_REIMBURSEMENT_FORM SET SUPERVISOR_APPROVAL_EXIST='Y' WHERE TRF_ID=I.TRF_ID;
             INSERT INTO MESSAGES (USER_ID,MESSAGE, TRF_ID, FLAG) VALUES (I.USER_ID, 'Your TRF Form has been autoapproved by your direct supervisor.', I.TRF_ID, 'SA');

        ELSIF (I.HEAD_APPROVAL_EXIST ='N' AND I.DAYS BETWEEN 1 AND 2) THEN
             UPDATE TUITION_REIMBURSEMENT_FORM SET HEAD_APPROVAL_EXIST='Y' WHERE TRF_ID=I.TRF_ID;
             INSERT INTO MESSAGES (USER_ID,MESSAGE, TRF_ID, FLAG) VALUES (I.USER_ID, 'Your TRF Form has been autoapproved by your department head.', I.TRF_ID, 'DA');
        ELSIF (I.BC_APPROVAL='N' AND I.DAYS < 1) THEN
            INSERT INTO MESSAGES (USER_ID, MESSAGE, TRF_ID, FLAG) SELECT 15, 'YELL AT BENCO FOR NOT APPROVING OR DENYING THIS TRF FORM.', I.TRF_ID, 'ZZ' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MESSAGES WHERE TRF_ID=I.TRF_ID AND USER_ID=15);
        END IF;
        END LOOP;
END;
/

