/*2.1 SELECT ALL FROM EMPLOYEE */
SELECT * FROM employee;
/*2.1 SELECT ALL FROM EMPLOYEE WHERE THE LAST NAME IS KING*/
SELECT * FROM employee WHERE lastname='King';
/*2.1 SELECT ALL FROM EMPLOYEE WHERE THE FIRST NAME IS ANDREW AND REPORTSO IS NULL*/
SELECT * FROM employee WHERE firstname='Andrew';
/*2.2 SELECT ALL FROM ALBUMS AND SORT THE REULT IN DESCENDING ORDER*/
SELECT *  FROM album ORDER BY TITLE DESC;
/*2.2 SELECT FIRST NAME FROM CUSTOMER AND SORT IN ASCENDING ORDER BY CITY*/
SELECT firstname FROM customer ORDER BY city ASC;
