DROP TABLE TRANSACTIONS;
DROP TABLE ACCOUNT;
DROP TABLE ACCOUNTTYPE;
DROP TABLE TRANS_TYPE;
DROP TABLE USERS;
DROP TABLE CLEARANCE_LEVEL;

DROP SEQUENCE SQ_USER_PK;
DROP SEQUENCE SQ_ACCT_ID;
DROP SEQUENCE SQ_TRANS_ID;

DROP PROCEDURE DELETE_ACCOUNT;


--TABLE CREATION
CREATE TABLE USERS
(USERID NUMBER NOT NULL,
CLEARANCEID NUMBER DEFAULT 2,
USERNAME VARCHAR2(40) NOT NULL,
PASSWORD VARCHAR2(40) NOT NULL,
FIRSTNAME VARCHAR2(40),
LASTNAME VARCHAR2(40),
ADDRESS VARCHAR2(50),
CITY VARCHAR2(40),
STATE VARCHAR2(40),
ZIP NUMBER(10),
AREACODE NUMBER(10),
PHONE NUMBER(15),
SOCIAL NUMBER(20) NOT NULL,
LASTFOUR NUMBER(10)NOT NULL,
CONSTRAINT PK_USER PRIMARY KEY (USERID)
);

CREATE TABLE ACCOUNTTYPE
(TYPEID NUMBER NOT NULL,
TYPENAME VARCHAR2(40),
CONSTRAINT PK_TYPEID PRIMARY KEY (TYPEID)
);


CREATE TABLE ACCOUNT
(ACCOUNTID NUMBER NOT NULL,
USERID NUMBER NOT NULL,
TYPEID NUMBER NOT NULL,
BALANCE NUMBER(30,2),
CONSTRAINT PK_ACCOUNTID PRIMARY KEY(ACCOUNTID)
);

CREATE TABLE CLEARANCE_LEVEL
(CLEARANCEID NUMBER NOT NULL,
CLEARANCE VARCHAR2(40),
CONSTRAINT PK_CLEARANCEID PRIMARY KEY(CLEARANCEID)
);

CREATE TABLE TRANSACTIONS 
(TRANSACTIONID NUMBER NOT NULL,
ACCOUNTID NUMBER NOT NULL,
TYPEID NUMBER NOT NULL,
TRANSACTIONVALUE NUMBER(30,2),
ENDINGBALANCE NUMBER(30,2),
CONSTRAINT PK_TRANS_ID PRIMARY KEY (TRANSACTIONID)
);

CREATE TABLE TRANS_TYPE
(TYPEID NUMBER NOT NULL,
TYPEDESC VARCHAR2(40),
CONSTRAINT PK_TYPE PRIMARY KEY(TYPEID)
);

--FOERIEGN KEYS
ALTER TABLE USERS ADD CONSTRAINT FK_CLEARANCEID
    FOREIGN KEY (CLEARANCEID) REFERENCES CLEARANCE_LEVEL (CLEARANCEID);
    
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_USERID
    FOREIGN KEY (USERID) REFERENCES USERS (USERID);

ALTER TABLE ACCOUNT ADD CONSTRAINT FK_TYPE_ID
    FOREIGN KEY (TYPEID) REFERENCES ACCOUNTTYPE (TYPEID);

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_ACCOUNTID
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT (ACCOUNTID);

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TYPEID
    FOREIGN KEY (TYPEID) REFERENCES TRANS_TYPE (TYPEID);

--SEQUENCE CREATION
CREATE SEQUENCE SQ_USER_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_ACCT_ID
START WITH 1110000000
INCREMENT BY 1;

CREATE SEQUENCE SQ_TRANS_ID
START WITH 10000
INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE DELETE_ACCOUNT(
        A_ACCOUNTID IN ACCOUNT.ACCOUNTID%TYPE,
        A_USERID IN ACCOUNT.USERID%TYPE)
IS
BEGIN
COMMIT;
DELETE FROM ACCOUNT
WHERE A_ACCOUNTID = ACCOUNTID AND A_USERID = USERID;
COMMIT;
END;
/

--INSERTING VALUES FOR LOOKUP TABLES
INSERT INTO ACCOUNTTYPE VALUES(1,'CHECKING');
INSERT INTO ACCOUNTTYPE VALUES(2,'SAVINGS');

INSERT INTO CLEARANCE_LEVEL VALUES(1,'ADMIN');
INSERT INTO CLEARANCE_LEVEL VALUES(2,'USER');

INSERT INTO TRANS_TYPE VALUES(1,'DEPOSIT');
INSERT INTO TRANS_TYPE VALUES(2,'WITHDRAWL');

--INSERTING INTO USER TABLE FIRST ENTRY ADMINISTRATOR
INSERT INTO USERS VALUES(SQ_USER_PK.NEXTVAL,1,'robin','Password','Robin','Avila','116 Timbercreekpine cir','Winter Garden','FL',34787,407,6151303,123456789,6789);
commit;


