INSERT INTO MediaType  VALUES (6, 'Test');
Delete from MEdiatype  where name= 'Test';

--SELECT AGGREGATE FROM GROUP BY HAVING
SELECT COUNT(EMPLOYEEID),COUNTRY,CITY FROM EMPLOYEE 
GROUP BY COUNTRY,CITY HAVING COUNT(EMPLOYEEID)>1;
 
 --AGGREGATE FUNCTIONS  
 SELECT MIN(UNITPRICE),MAX(UNITPRICE),COUNT(TRACKID) FROM TRACK;  